# Generated by Django 6.0.7 on 2026-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerposition',
            name='team',
            field=models.CharField(choices=[('home', 'Home'), ('away', 'Away')], default='home', max_length=4),
        ),
    ]
