# Generated by Django 6.0.7 on 2026-07-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0002_playerposition_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementArrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField()),
                ('start_y', models.FloatField()),
                ('end_x', models.FloatField()),
                ('end_y', models.FloatField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrows', to='tactics.formation')),
            ],
        ),
    ]
