# Generated by Django 6.0.7 on 2026-07-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0003_movementarrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='ball_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='ball_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
